WIP Numerical
siemens/OOASP pull request #27
Opened 2023-09-04 15:39 UTC by susuhahnml

2023-09-12 15:59 UTC, rtaupe requested changes
I reviewed only part of the PR. Is it already ready for merge after review? If no, please convert it to a draft.

2023-09-12 15:59 UTC, rtaupe commented on asp_interactive_configuration/examples/metro/constraints.lp
> +ooasp_cv(standingroom_iff_handrail,W,"Handrail required if stanfing rum is {}",(STANDINGROOM,new_object)):-
```suggestion
ooasp_cv(standingroom_iff_handrail,W,"Handrail required if standing room is {}",(STANDINGROOM,new_object)):-
```

2023-09-12 15:59 UTC, rtaupe commented on asp_interactive_configuration/examples/metro/fconstraints.lp
> +ooasp_cv(nrpassengers_neq_nrseats_plus_standingroom,new_object,"Number of passenges not adding up",(new_object,)):-
```suggestion
ooasp_cv(nrpassengers_neq_nrseats_plus_standingroom,new_object,"Number of passengers not adding up",(new_object,)):-
```

2023-09-12 15:59 UTC, rtaupe commented on asp_interactive_configuration/ooasp/config.py
> +        # print(values)
please remove commented-out code

2023-09-12 15:59 UTC, rtaupe commented on asp_interactive_configuration/ooasp/interactive.py
> +        # self.theory.on_model(model)
please do not include commented-out code

2023-09-12 15:59 UTC, rtaupe commented on asp_interactive_configuration/ooasp/interactive.py
> +            # config = self.config
please do not include commented-out code

2023-10-11 22:27 UTC, susuhahnml commented
The fixes to these comments were integrated into the cautious branch.

2023-10-11 22:27 UTC, closed without merging