Benchmarks
siemens/OOASP pull request #29
Opened 2023-09-15 10:21 UTC by ThmsMoritz

Added methods incremental_input_before and incremental_input_in_steps to allow for more dynamic benchmarks execution.

2023-09-15 11:31 UTC, gschennersie submitted a review, later dismissed

2023-09-18 11:03 UTC, ThmsMoritz commented
The automated benchmarks may require a small bit of adjusting. Currently 49 single, 27 double and 16 triple benchmarks are run (meaning the iterations/how often objects were added).

Most cases will still result in a timeout, which hopefully will change after the rackDouble bug is fixed.

2023-09-19 12:04 UTC, rtaupe requested changes
Thank you for these contributions!
Please address the comments and also update the description of the pull request (it seems that much more than just adding the methods `incremental_input_before` and `incremental_input_in_steps` has happened).

2023-09-19 12:04 UTC, rtaupe commented on asp_interactive_configuration/benchmarks/benchmark.py
> +def setup_bm_instance(elemAs, elemBs, elemCs, elemDs):
Please provide docstrings for the newly introduced methods

2023-09-19 12:04 UTC, rtaupe commented on asp_interactive_configuration/benchmarks/benchmark.py
> +def run_incremental_benchmarks(run_in_seconds: int):
This (and other) method(s) is never called. If this is the main method running all benchmarks, please add a sample call at the end of the file. In the end, there should be no methods that are not called from anywhere.

2023-09-19 12:04 UTC, rtaupe commented on asp_interactive_configuration/benchmarks/benchmark.py
> +    #thread = threading.Thread(target=extend_incrementally_wrapper, args=(iconf, found))
Please do not include commented-out code.

2023-09-19 12:04 UTC, rtaupe commented on asp_interactive_configuration/benchmarks/benchmark.py
> +    #if interrupted; console wont work anymore
Please have a look at https://github.com/potassco/clingo/issues/151 to improve handling of interrupts and/or timeouts.

2023-09-19 14:38 UTC, ThmsMoritz commented
Addressed mentioned issues, still missing the fix for handling of the timeout.

2023-09-22 09:26 UTC, ThmsMoritz commented
Still open:

- Proper termination of solve thread in `interactive._next_solution()` (currently iterator is implicitly waiting for termination of solving)
- Dynamic parametrizable timeout, hand over time out limit (reduced from iteration to iteration) from `interactive.extend_incrementally()`
- Prevent further iterations in case of timeout

2024-08-13 07:42 UTC, rtaupe commented
Closed, will be superseded by a declarative definition of benchmarks.

2024-08-13 07:42 UTC, closed without merging