Object bounds
siemens/OOASP pull request #60
Opened 2024-09-26 22:28 UTC by susuhahnml

2024-09-27 07:09 UTC, rtaupe requested changes
Thank you!
I just have a few questions to address, please.

2024-09-27 07:09 UTC, rtaupe commented on ooasp_configuration.lp
What is this file why has it changed?
Should it really be under version control?

2024-09-27 07:09 UTC, rtaupe commented on ooasp_configuration_wrong.lp
What is this file why has it changed?
Should it really be under version control?

2024-09-27 07:09 UTC, rtaupe commented on ooasp/encodings/ooasp_guess.lp
> +% Fact used in the UI to indentify objects that must be included
```suggestion
% Fact used in the UI to identify objects that must be included
```

2024-09-27 16:22 UTC, susuhahnml commented on ooasp_configuration.lp
This two files were generated output. I just removed them

2024-09-30 07:24 UTC, rtaupe approved these changes
Thank you!

2024-09-30 07:24 UTC, merged