Rest API implementation for usage with custom UI
siemens/OOASP pull request #71
Opened 2024-12-16 09:06 UTC by Kriplingo

Changes add two files, one (`ProjectManagerInterface.py`) containing main functionality for management of files representing domains and configurations accessible as part of the UI. File `solver_api.py` contains definitions of all endpoints and added functionality to format data into state required by the front-end application.

2024-12-17 13:20 UTC, rtaupe requested changes
Looks like a great contribution, thank you very much!
Please just address my minor suggestions.

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/file_manager/ProjectManagerInterface.py
> +        print(f"Project with this name ({self.name}) already exists.")
I suggest to move this before the `if`, would make it a bit clearer in my opinion

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/file_manager/ProjectManagerInterface.py
> +                        }
There's a certain redundancy with lines 68-76, can this be avoided?

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/file_manager/ProjectManagerInterface.py
> +        dom = Domain()._load(os.path.join(self.domain_path, name, "domain_conf.json"))
There's a constant for the magic string "domain_conf.json", please use it everywhere

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/file_manager/ProjectManagerInterface.py
It would be great to have at least brief docstrings for the (most important) functions in this file

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/file_manager/ProjectManagerInterface.py
> +        # TODO find all corresponding files and orphan them
Could you still do this? What does "orphan" mean exactly in this context?

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/file_manager/ProjectManagerInterface.py
> +        os.makedirs(Path("./interactive_configurator_files/configuration_files"), exist_ok=True)
Can `make_file_structure` be used here?

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/solver_api.py
> +        """
there seems to be too much indentation

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/file_manager/ProjectManagerInterface.py
Please add the copyright lines to new Python files (this and others)

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/solver_api.py
> +                    "position": {"x": random.randint(20, 200), "y": random.randint(20, 200)},
what is happening here?

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/solver_api.py
> +    Represents list of objects and associations a collection of nodes and edges.
Not just nodes and edges, there seem to be also colours and positions and stuff... Please expand the docstring a little bit.

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/solver_api.py
> +    print("Fisnished Solving")
typo

2024-12-17 13:20 UTC, rtaupe commented on ooasp/REST/solver_api.py
> +           }  # smart-suggestions currently do not have a pracical use, but might be useful in future
What are smart suggestions?

2024-12-18 14:11 UTC, rtaupe requested changes

2024-12-18 14:11 UTC, rtaupe commented on ooasp/REST/file_manager/ProjectManagerInterface.py
> +        else:
Please remove the `else`, there's a `return` right above it

2024-12-18 14:30 UTC, Kriplingo commented
Resolved conflicts, fixed typo, added required dependencies to poetry and `pyproject.toml`

2024-12-18 14:40 UTC, rtaupe approved these changes
Thank you!

2024-12-18 14:40 UTC, merged